"""add table task

Revision ID: f0a15db494b0
Revises: 0c582ef87c6c
Create Date: 2018-12-05 13:03:58.212985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0a15db494b0'
down_revision = '0c582ef87c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idProject', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('describe', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('createDate', sa.DateTime(), nullable=True),
    sa.Column('startDate', sa.DateTime(), nullable=True),
    sa.Column('endDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idProject'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_createDate'), 'task', ['createDate'], unique=False)
    op.create_index(op.f('ix_task_startDate'), 'task', ['startDate'], unique=False)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    op.create_index(op.f('ix_task_title'), 'task', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_title'), table_name='task')
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_startDate'), table_name='task')
    op.drop_index(op.f('ix_task_createDate'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
